// // import type { Metadata } from "next";
// // import { Inter } from "next/font/google";
// // import "./globals.css";
// // import Providers from "./providers";
// // import ProtectedLayout from "./ProtectedLayout";  // Adjust the import path as needed

// // const inter = Inter({ subsets: ["latin"] });

// // export const metadata: Metadata = {
// //   title: "IIIT DWD CGC",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body className={inter.className}>
// //         <Providers>
// //           {children}
// //         </Providers>
// //       </body>
// //     </html>
// //   );
// // }



// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Sidebar from "./(components)/(Sidebar)/Sidebar";
// import Providers from "./providers";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Providers>
//           <Sidebar />
//           <div>{children}</div>
//         </Providers>
//       </body>
//     </html>
//   );
// }


"use client"

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./(components)/(Sidebar)/Sidebar";
import Providers from "./providers";
import { usePathname } from "next/navigation"; // To get the current route

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

 
  const hideSidebarRoutes = ["/signin", "/signup"];

  const shouldHideSidebar = hideSidebarRoutes.includes(pathname);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {!shouldHideSidebar && <Sidebar />}
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
